# Site settings
title:  'ActSecure'
description: "On a quest for holistic security"
baseurl: "" 
url: "http://actsecure.github.io" 

# User settings
username: actsecure
user_title: ActSecure
email: actsecure@protonmail.com
twitter_username: actsecure
facebook_username: actsecure
github_username:  actsecure
gitter_username:  actsecure

# Guides listed on index
guides:
  - name: protest.guide
    url: http://www.protest.guide
  - name: Top 5 Cybersecurity Basics
    url: https://github.com/actsecure/resources/wiki/Top-5-Cybersecurity-Basics
  - name: Draft guides wiki
    url: https://github.com/actsecure/resources/wiki

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: blog
    url: /blog
  - title: guides
    url: /guides
  - title: tags
    url: /tags
  - title: about us
    url: /about

################################################### Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
