# Site settings
title:  'ActSecure'
description: "On a quest for holistic security"
baseurl: "" 
url: "http://hurtstotouchfire.github.io/actsecure.github.io" 
# for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: actsecure
user_title: ActSecure
email: actsecure@protonmail.com
twitter_username: actsecure
facebook_username: actsecure
github_username:  actsecure

# projects in header index
projects:
  - name: protest-guide
    url: https://github.com/actsecure/protest.guide
  - name: wiki
    url: https://github.com/actsecure/actsecure/wiki

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: posts
    url: /posts
  - title: tags
    url: /tags
  - title: about us
    url: /about

################################################### Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
