###########
# site.title, site.url, site.author.name

title:   'ActSecure'
author:
  name:  'ActSecure'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /jekyll-minimal-theme
url:  'https://actsecure.github.io/'

# http://henrythemes.github.io/jekyll-minimal-theme

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false

# Social Media
protonmail: 'mailto:actsecure@protonmail.com'
facebook: 'https://facebook.com/actsecure'
twitter: 'https://twitter.com/actsecure'
github: 'https://github.com/actsecure/'
